# Generated by Django 5.2.17 on 2026-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=30)),
                ('security_id', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(blank=True, max_length=30)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
