# Generated by Django 5.2.17 on 2026-09-21 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EIPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ip', models.GenericIPAddressField(unique=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('is_allocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_port', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='proxy.eippool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_allocation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
